30/Jan/2023 15:57:28 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /news/ (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name."), <traceback object at 0x7fb990539b80>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
30/Jan/2023 15:57:28 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /news/ HTTP/1.1" 500 203422 None
31/Jan/2023 16:14:03 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /news/ (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 15: 'get_available_languages'. Did you forget to register or load this tag?"), <traceback object at 0x7f74a23d7c80>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_available_languages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 206, in select_template
    return self.get_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 15: 'get_available_languages'. Did you forget to register or load this tag?
31/Jan/2023 16:14:03 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /news/ HTTP/1.1" 500 256476 None
31/Jan/2023 16:14:24 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /news/ (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 15: 'get_available_languages'. Did you forget to register or load this tag?"), <traceback object at 0x7f74a23dcd80>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_available_languages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 206, in select_template
    return self.get_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 15: 'get_available_languages'. Did you forget to register or load this tag?
31/Jan/2023 16:14:24 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /news/ HTTP/1.1" 500 256476 None
31/Jan/2023 16:16:59 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /welcome/ (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 16: 'get_available_languages'. Did you forget to register or load this tag?"), <traceback object at 0x7f74a2162e80>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_available_languages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_response(request, response)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/contrib/flatpages/middleware.py", line 12, in process_response
    return flatpage(request, request.path_info)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/contrib/flatpages/views.py", line 45, in flatpage
    return render_flatpage(request, f)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/contrib/flatpages/views.py", line 70, in render_flatpage
    return HttpResponse(template.render({"flatpage": f}, request))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 206, in select_template
    return self.get_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 16: 'get_available_languages'. Did you forget to register or load this tag?
31/Jan/2023 16:16:59 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /welcome/ HTTP/1.1" 500 224960 None
02/Feb/2023 14:18:40 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /news/assets/favicon.ico (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7fb560ac4c40>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:18:41 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /news/assets/favicon.ico HTTP/1.1" 500 62402 None
02/Feb/2023 14:18:42 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /admin/news/categories/ (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7fb560b17e80>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:18:42 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /admin/news/categories/ HTTP/1.1" 500 62870 None
02/Feb/2023 14:18:43 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /favicon.ico (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7fb560b3eb00>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:18:43 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /favicon.ico HTTP/1.1" 500 62316 None
02/Feb/2023 14:50:20 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /news/ (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7f0f8acac2c0>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:50:20 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /news/?page=3 HTTP/1.1" 500 63141 None
02/Feb/2023 14:50:20 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /favicon.ico (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7f0f8aa436c0>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:50:20 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /favicon.ico HTTP/1.1" 500 62306 None
02/Feb/2023 14:53:29 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /news/ (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7f0f8998fc80>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:53:29 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /news/?page=3 HTTP/1.1" 500 63141 None
02/Feb/2023 14:53:29 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /favicon.ico (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7f0f8aa56d80>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:53:29 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /favicon.ico HTTP/1.1" 500 62306 None
02/Feb/2023 14:53:53 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /news/ (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7f0f8aa7de80>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:53:53 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /news/ HTTP/1.1" 500 62528 None
02/Feb/2023 14:53:53 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /favicon.ico (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7f0f8aa86180>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:53:53 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /favicon.ico HTTP/1.1" 500 62299 None
02/Feb/2023 14:54:18 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /news/ (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7f6577bd6bc0>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:54:18 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /news/ HTTP/1.1" 500 62665 None
02/Feb/2023 14:54:19 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /favicon.ico (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7f6577c137c0>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:54:19 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /favicon.ico HTTP/1.1" 500 62299 None
02/Feb/2023 14:57:28 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /news/ (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7f19ec9a9440>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:57:28 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /news/ HTTP/1.1" 500 62665 None
02/Feb/2023 14:57:28 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /favicon.ico (<class 'TypeError'>, TypeError("'TimezoneMiddleware' object is not callable"), <traceback object at 0x7f19ec76b780>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
TypeError: 'TimezoneMiddleware' object is not callable
02/Feb/2023 14:57:28 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /favicon.ico HTTP/1.1" 500 62299 None
02/Feb/2023 15:01:36 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/utils/log.py Internal Server Error: /news/ (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError('timezone requires 2 arguments, 1 provided'), <traceback object at 0x7fa42cf2e780>)
Traceback (most recent call last):
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 699, in __init__
    self.args_check(filter_name, filter_func, args)
  File "/home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/template/base.py", line 761, in args_check
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: timezone requires 2 arguments, 1 provided
02/Feb/2023 15:01:36 ERROR /home/user/SkillFactory/PyProjects/News_Portal/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py "GET /news/ HTTP/1.1" 500 244608 None
